/* Shared chrome for FAMA v2 pages: nav + footer injected into #nav / #footer placeholders */
(function(){
const L='../../assets/logo/svg/';
const nav=`<a href="Home.html"><img src="${L}fama-academy-mark-white.svg" alt="FAMA Academy" style="height:20px"></a><ul class="lbl"><li><a href="MasterMadrid.html">Máster</a></li><li><a href="MetodoFama.html">Método FAMA</a></li><li><a href="https://models.famaacademy.es/">Modelos</a></li><li><a href="Online.html">Online</a></li><li><a href="Contacto.html">Contacto</a></li></ul><div class="navr"><a class="btn navbtn" href="{{cta}}">{{ctaLabel}}</a><button class="menubtn lbl" type="button" aria-label="Menú">Menú</button></div>`;
const panel=`<div class="menu" id="menu"><div class="menuhead"><img src="${L}fama-academy-mark-white.svg" alt="FAMA Academy" style="height:20px"><button class="menubtn lbl" type="button" aria-label="Cerrar">Cerrar</button></div><ul><li><a href="Home.html">Inicio</a></li><li><a href="Openday.html">Openday</a></li><li><a href="MasterMadrid.html">Máster · Madrid</a></li><li><a href="MasterBarcelona.html">Máster · Barcelona</a></li><li><a href="IntensivoVerano.html">Intensivos de verano</a></li><li><a href="Online.html">Online</a></li><li><a href="MetodoFama.html">Método FAMA</a></li><li><a href="Blog.html">Blog</a></li><li><a href="FamaAcademy.html">FAMA Academy</a></li><li><a href="https://models.famaacademy.es/">Modelos</a></li><li><a href="Contacto.html">Contacto</a></li></ul><div class="menufoot lbl dim"><span>Madrid · Barcelona</span><a href="https://www.instagram.com/famaacademy">Instagram</a></div></div>`;
const foot=`<div class="cols r">
<div><span class="lbl dim">Explora</span><ul><li><a href="MetodoFama.html">Método FAMA</a></li><li><a href="FamaAcademy.html">FAMA Academy</a></li><li><a href="Blog.html">Blog</a></li><li><a href="Contacto.html">Contacto</a></li><li><a href="Faq.html">Preguntas frecuentes</a></li><li><a href="EscuelaMadrid.html">Escuela de modelos en Madrid</a></li></ul></div>
<div><span class="lbl dim">Recursos</span><ul><li><a href="ComoSerModelo.html">Cómo ser modelo</a></li><li><a href="Castings.html">Castings</a></li><li><a href="Autoestima.html">Autoestima y confianza</a></li><li><a href="Padres.html">Para padres</a></li><li><a href="CursoCasting.html">Curso online de Casting</a></li><li><a href="CursoPosado.html">Curso online de Posado</a></li></ul></div>
<div><span class="lbl dim">Legal</span><ul><li><a href="AvisoLegal.html">Aviso legal</a></li><li><a href="Privacidad.html">Política de privacidad</a></li><li><a href="Cookies.html">Política de cookies</a></li><li><a href="CondicionesGenerales.html">Condiciones generales</a></li></ul></div>
<div><span class="lbl dim">Grupo</span><ul><li><a href="https://famamanagement.com/">FAMA Management</a></li><li><a href="https://famaspaces.es/">FAMA Spaces</a></li><li><a href="https://famaacademy.es">FAMA Academy</a></li><li><a href="https://famaagency.es">FAMA Agency</a></li></ul></div>
<div><span class="lbl dim">RRSS</span><ul><li><a href="https://www.instagram.com/famaacademy">Instagram</a></li><li><a href="https://www.tiktok.com/@famaacademy">Tiktok</a></li><li><a href="https://www.youtube.com/@famaacademy_escuelamodelos/">Youtube</a></li></ul></div>
</div>
<div class="bottom"><img src="${L}fama-academy-mark-white.svg" alt="FAMA Academy"><span>© 2026 FAMA Academy. Madrid · Barcelona.</span></div>`;
const n=document.getElementById('nav');if(n&&n.dataset.minimal){n.className='wrap';n.innerHTML='<a href="Home.html"><img src="'+L+'fama-academy-mark-white.svg" alt="FAMA Academy" style="height:20px"></a><span class="lbl" style="color:#D0D0D0">'+(n.dataset.label||'Admisión · Máster Modelo Profesional')+'</span>';}else if(n){n.className='wrap';n.innerHTML=nav.replace('{{cta}}',n.dataset.cta||'MasterMadrid.html#convocatorias').replace('{{ctaLabel}}',n.dataset.label||'Solicitar plaza');n.insertAdjacentHTML('afterend',panel);const menu=document.getElementById('menu');document.querySelectorAll('.menubtn').forEach(b=>b.addEventListener('click',()=>{menu.classList.toggle('open');document.body.style.overflow=menu.classList.contains('open')?'hidden':'';}));}
const f=document.getElementById('footer');if(f&&f.dataset.minimal){f.className='band';f.style.paddingTop='0';f.innerHTML='<div class="bottom" style="border-top:1px solid rgba(255,255,255,.18)"><img src="'+L+'fama-academy-mark-white.svg" alt="FAMA Academy"><span class="lbl dim" style="display:flex;gap:24px;flex-wrap:wrap"><a href="CondicionesGenerales.html">Condiciones generales</a><a href="Privacidad.html">Privacidad</a><a href="mailto:hola@famaacademy.es">hola@famaacademy.es</a></span></div>';}else if(f){f.className='band';f.style.paddingTop='0';f.innerHTML=foot;}
})();
